apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: nic01/snkrhub_graphql-gateway:latest
          volumeMounts:
            - name: supergraph-volume
              mountPath: /etc/config
          env:
            - name: APOLLO_SCHEMA_CONFIG_EMBEDDED
              value: 'true'
          ports:
            - containerPort: 3000
      volumes:
        - name: supergraph-volume
          configMap:
            name: supergraph # from kustomization.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  selector:
    app: router
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router-service
                port:
                  number: 4000
