apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: nic01/snkrhub_graphql-gateway:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: supergraph-volume
              mountPath: /etc/config
          env:
            - name: APOLLO_KUBERNETES_HOST
              value: 'true'
          envFrom:
            - secretRef:
                name: gateway-secret
          ports:
            - containerPort: 3000
      volumes:
        - name: supergraph-volume
          configMap:
            name: supergraph # from kustomization.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 3000


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: snkrhub.xyz
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
