version: '3.8'
services:
  # ---------------------------
  # GraphQL Gateway
  # ---------------------------
  # graphql-gateway:
  #   build:
  #     context: .
  #     dockerfile: ./gateway/Dockerfile.dev
  #     args:
  #       NODE_ENV: development
  #   volumes:
  #     - ./gateway:/usr/local/apps/gateway-app/dev
  #     # - exclude:/usr/local/apps/gateway-app/dev/node_modules/
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev

  # ---------------------------
  # Inventory microservice
  # ---------------------------
  inventory-microservice:
    build:
      context: ./inventory-microservice
      dockerfile: ./Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ./inventory-microservice:/usr/local/apps/inventory-app/dev
      # - exclude:/usr/local/apps/inventory-app/dev/node_modules/
    environment:
      - NODE_ENV=development
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=inventory-microservice
      - POSTGRES_DATABASE=snkrhub_inventory
      - SESSION_SECRET=secret
    env_file:
      - ./inventory-microservice/.env
    command: npm run dev
    depends_on:
      - inventory-microservice_db

  inventory-microservice_db:
    hostname: 'inventory-microservice_db'
    image: postgres
    volumes:
      - inventory-microservice_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=inventory-microservice
      - POSTGRES_INITDB_ROOT_PASSWORD=inventory-microservice

  # ---------------------------
  # Analytics microservice
  # ---------------------------
  analytics-microservice:
    build:
      context: ./analytics-microservice
      dockerfile: ./Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ./analytics-microservice:/usr/local/apps/analytics-app/dev
      # - exclude:/usr/local/apps/inventory-app/dev/node_modules/
    environment:
      - NODE_ENV=development
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=analytics-microservice
      - POSTGRES_DATABASE=snkrhub_analytics
      - SESSION_SECRET=secret
    env_file:
      - ./analytics-microservice/.env
    command: npm run dev
    depends_on:
      - analytics-microservice_db

  analytics-microservice_db:
    hostname: 'analytics-microservice_db'
    image: postgres
    volumes:
      - analytics-microservice_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=analytics-microservice
      - POSTGRES_INITDB_ROOT_PASSWORD=analytics-microservice

# Create a volume to persist data
volumes:
  inventory-microservice_db:
  analytics-microservice_db:
