version: '3.8'
services:
  # ---------------------------
  # Inventory microservice
  # ---------------------------
  inventory-microservice:
    container_name: 'inventory-microservice'
    hostname: 'inventory-microservice'
    build: ./inventory-microservice
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
