version: '3.8'
services:
  # ---------------------------
  # GraphQL Gateway
  # ---------------------------
  graphql-gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile.test
      args:
        NODE_ENV: test
    volumes:
      - ./gateway:/usr/local/apps/gateway-app/test
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=test
      - PORT=3000
    command: npm run test

  # ---------------------------
  # Inventory microservice
  # ---------------------------
  inventory-microservice:
    build:
      context: ./inventory-microservice
      dockerfile: ./Dockerfile.test
      args:
        NODE_ENV: test
    volumes:
      - ./inventory-microservice:/usr/local/apps/inventory-app/test
    environment:
      - NODE_ENV=test
      - POSTGRES_IP=postgres-inventory-test-db
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=inventory-microservice
      - POSTGRES_DATABASE=postgres
      - SESSION_SECRET=secret
    command: npm run test
    depends_on:
      - postgres-inventory-test-db

  postgres-inventory-test-db:
    image: postgres
    volumes:
      - postgres-inventory-test-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=inventory-microservice
      - POSTGRES_INITDB_ROOT_PASSWORD=inventory-microservice

  # ---------------------------
  # Inventory microservice
  # ---------------------------
  analytics-microservice:
    build:
      context: ./analytics-microservice
      dockerfile: ./Dockerfile.test
      args:
        NODE_ENV: test
    volumes:
      - ./analytics-microservice:/usr/local/apps/analytics-app/test
    environment:
      - NODE_ENV=test
      - POSTGRES_IP=postgres-analytics-test-db
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=analytics-microservice
      - POSTGRES_DATABASE=postgres
      - SESSION_SECRET=secret
    command: npm run test
    depends_on:
      - postgres-analytics-test-db

  postgres-analytics-test-db:
    image: postgres
    volumes:
      - postgres-analytics-test-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=analytics-microservice
      - POSTGRES_INITDB_ROOT_PASSWORD=analytics-microservice

# Create a volume to persist data
volumes:
  postgres-inventory-test-db:
  postgres-analytics-test-db:
