version: '3.8'
services:
  inventory-microservice:
    build:
      # Location of dockerfile
      context: ./inventory-microservice
      # Pass all the different arguments
      args:
        NODE_ENV: development
    volumes:
      - ./inventory-microservice:/inventory-app:ro # Create a bind mount. First specify path to folder on local machine, then path to folder in docker container
      - /inventory-app/node_modules # Create anonymous volume to prevent the bind mount from overwriting the node_modules folder
    environment:
      - NODE_ENV=development
    command: npm run dev
