version: '3.8'
services:
  # ---------------------------
  # GraphQL Gateway
  # ---------------------------
  graphql-gateway:
    restart: always
    build:
      context: ./gateway
      args:
        NODE_ENV: development
    volumes:
      - ./gateway:/usr/local/apps/gateway-app/dev
      - exclude:/usr/local/apps/gateway-app/dev/node_modules/
    environment:
      - NODE_ENV=development
    command: npm run dev

  # ---------------------------
  # Inventory microservice
  # ---------------------------
  inventory-microservice:
    restart: always
    build:
      context: ./inventory-microservice
      args:
        NODE_ENV: development
    volumes:
      - ./inventory-microservice:/usr/local/apps/inventory-app/dev
      - exclude:/usr/local/apps/inventory-app/dev/node_modules/
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  exclude:
