version: '3.8'
services:
  # ---------------------------
  # GraphQL Gateway
  # ---------------------------
  # graphql-gateway:
  #   container_name: 'graphql-gateway'
  #   hostname: 'graphql-gateway'
  #   build: ./gateway
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - PORT=3000

  # ---------------------------
  # Inventory microservice
  # ---------------------------
  inventory-microservice:
    container_name: 'inventory-microservice'
    hostname: 'inventory-microservice'
    build: ./inventory-microservice
    ports:
      - '3001:3001'
    environment:
      - PORT=3001

  # ---------------------------
  # Analytics microservice
  # ---------------------------
  analytics-microservice:
    container_name: 'analytics-microservice'
    hostname: 'analytics-microservice'
    build: ./analytics-microservice
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
