version: '3.8'
services:
  # ---------------------------
  # Inventory microservice
  # ---------------------------
  inventory-microservice:
    build:
      # Location of dockerfile
      context: ./inventory-microservice
      # Pass all the different arguments
      args:
        NODE_ENV: development
      volumes:
        # Create a bind mount. First specify path to folder on local machine, then path to folder in docker container
        - ./inventory-microservice:/inventory-microservice:ro
        # Create anonymous volume to prevent the bind mount from overwriting the node_modules folder
        - /inventory-microservice/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
