version: '3.8'
services:
  # ---------------------------
  # GraphQL Gateway
  # ---------------------------
  graphql-gateway:
    container_name: 'graphql-gateway'
    hostname: 'graphql-gateway'
    build:
      context: .
      dockerfile: ./gateway/Dockerfile.test
      args:
        NODE_ENV: test
    volumes:
      - ./gateway:/usr/local/apps/gateway-app/test
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=test
      - PORT=3000
    command: npm run test

  # ---------------------------
  # Inventory microservice
  # ---------------------------
  inventory-microservice:
    build:
      context: ./inventory-microservice
      dockerfile: ./Dockerfile.test
      args:
        NODE_ENV: test
    volumes:
      - ./inventory-microservice:/usr/local/apps/inventory-app/test
    environment:
      - NODE_ENV=test
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
      - SESSION_SECRET=secret
    env_file:
      - ./inventory-microservice/.env
    command: npm run test
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres-test-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_INITDB_ROOT_PASSWORD=example

# Create a volume to persist data
volumes:
  postgres-test-db:
