version: '3.8'
services:
  inventory-microservice:
    restart: always
    build:
      context: ./inventory-microservice
      args:
        NODE_ENV: development
    volumes:
      - ./inventory-microservice:/usr/local/apps/inventory-app/dev
      - exclude:/usr/local/apps/inventory-app/dev/node_modules/
    environment:
      - NODE_ENV=development
    command: npm run start:watch

volumes:
  exclude:
