federation_version: 2 # Without this line, Rover uses Federation 1
subgraphs:
  inventory:
    routing_url: http://localhost:3001/graphql
    schema:
      file: ./inventory-microservice/src/schema/inventory.graphql
