# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-db-config
  labels:
    app: inventory-db
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: inventory_microservice
  POSTGRES_DB: snkrhub_inventory
  PGDATA: /var/lib/postgresql/data/inventory/
---

# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-postgres-db-lb
spec:
  selector:
    app: inventory-db
  type: NodePort
  ports:
  - port: 5432


---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  serviceName: inventory-db-service
  selector:
    matchLabels:
      app: inventory-db
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: inventory-db
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: inventory-postgresql-db-disk
              mountPath: /var/lib/postgresql/data
          envFrom:
            - configMapRef:
                name: inventory-db-config

# Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: inventory-postgresql-db-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi