# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
	name: inventory-db-config
	labels:
		app: inventory-db
data:
	POSTGRES_USER: postgres
	POSTGRES_PASSWORD: inventory-microservice
	POSTGRES_DB: postgres
	PGDATA: /data/pgdata
---

# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
	name: inventory-postgres-db-lb
spec:
	selector:
		app: inventory-db
	type: LoadBalancer
	ports:
	- port: 5432
	targetPort: 5432

---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
	name: inventory-db
spec:
	serviceName: inventory-db-service
	selector:
		matchLabels:
			app: inventory-db
	replicas: 2
	template:
		metadata:
			labels:
				app: inventory-db
		spec:
			# Official Postgres Container
			containers:
			- name: inventory-db
			image: postgres
			imagePullPolicy: IfNotPresent
			ports:
			- containerPort: 5432
			
      # Resource Limits
			resources:
				requests:
					memory: "265Mi"
					cpu: "250m"
				limits:
					memory: "512Mi"
					cpu: "500m"
			
      # Data Volume
			volumeMounts:
			- name: inventory-postgresql-db-disk
			  mountPath: /data
			
      # Point to ConfigMap
			env:
			- configMapRef:
			  name: inventory-db-config

# Volume Claim
volumeClaimTemplates:
	- metadata:
		name: inventory-postgresql-db-disk
	spec:
		accessModes: ["ReadWriteOnce"]
		resources:
			requests:
				storage: 5Gi